models/Cart.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 08.10.2017
 * Time: 0:09
 */

namespace app\models;


use Yii;
use yii\web\HttpException;

class Cart
{
    public function __construct()
    {
        Yii::$app->session->open();
    }

    public function addToCart($id, $quantity){
        $product = Product::find()->where(['id' => $id])->one();

        if(!$product)
            throw new HttpException(400, 'Invalid data parameters');

        if(isset($_SESSION['cart'][$id])) {
            $_SESSION['cart'][$id]['quantity'] += $quantity;
            $_SESSION['cart'][$id]['sum'] = $product->price * $_SESSION['cart'][$id]['quantity'];
        }
        else {
            $_SESSION['cart'][$id]['quantity'] = $quantity;
            $_SESSION['cart'][$id]['sum'] = $product->price * $quantity;
            $_SESSION['cart'][$id]['product_id'] = $id;
        }
    }

    public function deleteToCart($id, $quantity){

        if(isset($_SESSION['cart'][$id])) {
            $_SESSION['cart'][$id]['quantity'] -= $quantity;
        }elseif(!isset($_SESSION['cart'][$id])){
            throw new HttpException(400, 'Invalid data parameters');
        }
        if($_SESSION['cart'][$id]['quantity'] <= 0) {
            unset($_SESSION['cart'][$id]);
            return 'end';
        }
    }

    public function cart(){
        $arProduct = [];
        $total_sum = 0;

        foreach ($_SESSION['cart'] as $product){
            $arProduct['data']['product'][] = $product;
            $total_sum += $product['sum'];
        }
        $arProduct['data']['total_sum'] = $total_sum;
        $arProduct['data']['products_count'] = count($arProduct['data']['product']);

        return $arProduct;
    }

    public function product(){
        $result = Product::find()->all();
        $arProduct = [];
        foreach ($result as $key => $product){
            $arProduct['data'][$key]['id'] = $product->id;
            $arProduct['data'][$key]['name'] = $product->name;
            $arProduct['data'][$key]['description'] = $product->description;
            $arProduct['data'][$key]['price'] = $product->price;
        }
        return $arProduct;
    }

    public function __destruct()
    {
        Yii::$app->session->close();
    }
}

models/Product.php
<?php
namespace app\models;


use DateTime;
use yii\db\ActiveRecord;

/**
 * Created by PhpStorm.
 * User: root
 * Date: 02.10.2017
 * Time: 12:48
 */

class Product extends ActiveRecord
{
    public static function tableName()
    {
        return 'product';
    }

}

controllers/ApiController.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 07.10.2017
 * Time: 14:59
 */
namespace app\controllers;


use app\models\Cart;
use app\models\Product;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\Response;

class ApiController extends Controller
{
    public function actionAddToCart(){
        $id = Yii::$app->request->post('id');
        $quantity = Yii::$app->request->post('quantity');


        if(!preg_match('/^\d+$/', $id))
            throw new HttpException(400, 'Invalid data parameters');
        if(!preg_match('/^\d+$/', $quantity))
            throw new HttpException(400, 'Invalid data parameters');
        $cart = new Cart();
        $cart->addToCart($id, $quantity);

    }

    public function actionDeleteToCart(){
        $id = Yii::$app->request->post('id');
        $quantity = Yii::$app->request->post('quantity');


        if(!preg_match('/^\d+$/', $id))
            throw new HttpException(400, 'Invalid data parameters');
        if(!preg_match('/^\d+$/', $quantity))
            throw new HttpException(400, 'Invalid data parameters');


        $cart = new Cart();
        $res = $cart->deleteToCart($id, $quantity);
        return json_encode(['success' => $res]);
    }

    public function actionCart(){



        $cart = new Cart();
        if(empty($_SESSION['cart']))
            return 'Корзина пуста';
        $arProduct = $cart->cart();

        $response = Yii::$app->response;
        $response->format = Response::FORMAT_JSON;
        $response->data = $arProduct;
        return $response;
    }

    public function actionProducts(){
        $cart = new Cart();
        $arProduct = $cart->product();

        $response = Yii::$app->response;
        $response->format = Response::FORMAT_JSON;
        $response->data = $arProduct;
        return $response;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;


use app\models\Product;
use Yii;
use yii\web\Controller;


class SiteController extends Controller
{
    public function actionIndex()
    {
        Yii::$app->session->open();
        $products = Product::find()->all();
        return $this->render('index', compact('products'));
    }

    public function actionError(){
        $exception = Yii::$app->errorHandler->exception;
        if ($exception !== null) {
            $name = $exception->getName();
            $message = $exception->getMessage();
            $status = $exception->statusCode;
            return $this->render('error', compact('name', 'message', 'status'));
        }
    }
}

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

app\assets\AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DОСТРЕ html>
<html lang="<?= Yii::$app->language?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <?= Html::csrfMetaTags() ?>
</head>
<body>
<?php $this->beginBody() ?>
<nav class="navbar navbar-default">
    <div class="container">
            <ul class="nav navbar-nav navbar-right  ">
                  <li><a href="<?= Url::toRoute(['site/cart'])?>">Корзина</a></li>
            </ul>
    </div>
</nav>
<div class="container">
    <?= $content ?>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?> (#<?=$status;?>)</h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php foreach ($products as $product) :?>
<article class="col-sm-3 product">
    <h3><?=$product->name;?></h3>
    <div class="description"><?=$product->description;?></div>
    <div class="price">Цена: <?=$product->price;?></div>


        <input type="button" class="less count_operation" value="-">
        <input type="text" value='1' class="quantity"/>
        <input type="button" class="more count_operation" value="+">

    <input type="hidden" class="id" value="<?=$product->id;?>"/>
    <input type="button" class='addProduct' value="Добавить в корзину"/>
    <?php if(!empty($_SESSION['cart'][$product->id])) :?>
        <span class="del"><input type="button" class='deleteProduct' value="Удалить из корзины"/></span>
    <?php endif;?>
</article>
<?php endforeach;?>